// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int32 kind,
          ffi.Int32 severity,
          ffi.Pointer<ffi.Char> message,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_map_set_diagnostic_callback(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int32 kind,
        ffi.Int32 severity,
        ffi.Pointer<ffi.Char> message,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Uint64, ffi.Pointer<ffi.Char>)
>()
external int mbl_configure(
  ffi.Pointer<ffi.Char> cache_path,
  int max_cache_bytes,
  ffi.Pointer<ffi.Char> api_key,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> mbl_get_cache_path();

@ffi.Native<ffi.Int Function(ffi.Int32)>()
external int mbl_configure_tile_server(int server);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int mbl_set_http_headers(ffi.Pointer<ffi.Char> rules_json);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> mbl_http_headers_for_url(
  ffi.Pointer<ffi.Char> url,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Uint64 request_id,
          ffi.Int32 kind,
          ffi.Pointer<ffi.Char> url,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external int mbl_set_request_transform(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Uint64 request_id,
        ffi.Int32 kind,
        ffi.Pointer<ffi.Char> url,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external void mbl_transform_reply(int request_id, ffi.Pointer<ffi.Char> url);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Char>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Float,
    ffi.Int,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Pointer<ffi.Char> error,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_create_region(
  ffi.Pointer<ffi.Char> style_url,
  double north,
  double south,
  double east,
  double west,
  double min_zoom,
  double max_zoom,
  double pixel_ratio,
  int include_ideographs,
  ffi.Pointer<ffi.Uint8> metadata,
  int metadata_len,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Pointer<ffi.Char> error,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Pointer<ffi.Char> error,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_set_metadata(
  int region_id,
  ffi.Pointer<ffi.Uint8> metadata,
  int metadata_len,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Pointer<ffi.Char> error,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<ffi.Char> json,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_list_regions(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void> user, ffi.Pointer<ffi.Char> json)
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Int32)>()
external void mbl_offline_set_download_state(int region_id, int state);

@ffi.Native<
  ffi.Int Function(
    ffi.Int64,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Int32 state,
          ffi.Uint64 completed_resources,
          ffi.Uint64 required_resources,
          ffi.Int required_is_precise,
          ffi.Uint64 completed_bytes,
          ffi.Uint64 completed_tiles,
          ffi.Uint64 required_tiles,
          ffi.Uint64 completed_tile_bytes,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external int mbl_offline_get_region_status(
  int region_id,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Int32 state,
        ffi.Uint64 completed_resources,
        ffi.Uint64 required_resources,
        ffi.Int required_is_precise,
        ffi.Uint64 completed_bytes,
        ffi.Uint64 completed_tiles,
        ffi.Uint64 required_tiles,
        ffi.Uint64 completed_tile_bytes,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Int64,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Int32 state,
          ffi.Uint64 completed_resources,
          ffi.Uint64 required_resources,
          ffi.Int required_is_precise,
          ffi.Uint64 completed_bytes,
          ffi.Uint64 completed_tiles,
          ffi.Uint64 required_tiles,
          ffi.Uint64 completed_tile_bytes,
        )
      >
    >,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Int is_tile_limit,
          ffi.Pointer<ffi.Char> message,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external int mbl_offline_set_observer(
  int region_id,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Int32 state,
        ffi.Uint64 completed_resources,
        ffi.Uint64 required_resources,
        ffi.Int required_is_precise,
        ffi.Uint64 completed_bytes,
        ffi.Uint64 completed_tiles,
        ffi.Uint64 required_tiles,
        ffi.Uint64 completed_tile_bytes,
      )
    >
  >
  on_progress,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Int is_tile_limit,
        ffi.Pointer<ffi.Char> message,
      )
    >
  >
  on_error,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Int64,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Pointer<ffi.Char> error,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_delete_region(
  int region_id,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Pointer<ffi.Char> error,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Int64,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Pointer<ffi.Char> error,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_invalidate_region(
  int region_id,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Pointer<ffi.Char> error,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void mbl_offline_set_tile_count_limit(int limit);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Pointer<ffi.Char> error,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_pack_database(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Pointer<ffi.Char> error,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Pointer<ffi.Char> error,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_clear_ambient_cache(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Pointer<ffi.Char> error,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Pointer<ffi.Char> error,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_set_maximum_ambient_cache_size(
  int bytes,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Pointer<ffi.Char> error,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Int64 region_id,
          ffi.Pointer<ffi.Char> error,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_offline_reset_database(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user,
        ffi.Int64 region_id,
        ffi.Pointer<ffi.Char> error,
      )
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Pointer<MblMap> Function(
    ffi.Uint32,
    ffi.Uint32,
    ffi.Float,
    ffi.Pointer<ffi.Char>,
    ffi.Int,
  )
>()
external ffi.Pointer<MblMap> mbl_map_create(
  int width,
  int height,
  double pixel_ratio,
  ffi.Pointer<ffi.Char> style_uri,
  int continuous,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Pointer<ffi.Char>)>()
external void mbl_map_set_style(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> style_uri,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
  )
>()
external void mbl_map_set_camera(
  ffi.Pointer<MblMap> map,
  double lat,
  double lng,
  double zoom,
  double bearing,
  double pitch,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
  )
>()
external void mbl_map_get_camera(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Double> out_lat,
  ffi.Pointer<ffi.Double> out_lng,
  ffi.Pointer<ffi.Double> out_zoom,
  ffi.Pointer<ffi.Double> out_bearing,
  ffi.Pointer<ffi.Double> out_pitch,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Uint32, ffi.Uint32)>()
external void mbl_map_resize(ffi.Pointer<MblMap> map, int width, int height);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Double, ffi.Double)>()
external void mbl_map_move_by(ffi.Pointer<MblMap> map, double dx, double dy);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<MblMap>, ffi.Double, ffi.Double, ffi.Double)
>()
external void mbl_map_scale_by(
  ffi.Pointer<MblMap> map,
  double scale,
  double anchor_x,
  double anchor_y,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<MblMap>, ffi.Double, ffi.Double, ffi.Double)
>()
external void mbl_map_rotate_by(
  ffi.Pointer<MblMap> map,
  double degrees,
  double anchor_x,
  double anchor_y,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Double)>()
external void mbl_map_pitch_by(ffi.Pointer<MblMap> map, double degrees);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<ffi.Void> user, ffi.Uint64 token)
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_map_set_camera_finish_callback(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void> user, ffi.Uint64 token)
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<MblMap>, ffi.Pointer<MblCameraOptions>)
>()
external void mbl_map_jump_to(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<MblCameraOptions> camera,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<MblCameraOptions>,
    ffi.Pointer<MblAnimationOptions>,
    ffi.Uint64,
  )
>()
external void mbl_map_ease_to(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<MblCameraOptions> camera,
  ffi.Pointer<MblAnimationOptions> animation,
  int token,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<MblCameraOptions>,
    ffi.Pointer<MblAnimationOptions>,
    ffi.Uint64,
  )
>()
external void mbl_map_fly_to(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<MblCameraOptions> camera,
  ffi.Pointer<MblAnimationOptions> animation,
  int token,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>)>()
external void mbl_map_cancel_transitions(ffi.Pointer<MblMap> map);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<MblLatLngBounds>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Int32,
    ffi.Double,
    ffi.Int32,
    ffi.Double,
    ffi.Int32,
    ffi.Pointer<MblAnimationOptions>,
    ffi.Uint64,
  )
>()
external void mbl_map_fit_bounds(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<MblLatLngBounds> bounds,
  double pad_top,
  double pad_right,
  double pad_bottom,
  double pad_left,
  int has_bearing,
  double bearing,
  int has_pitch,
  double pitch,
  int mode,
  ffi.Pointer<MblAnimationOptions> animation,
  int token,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<MblLatLngBounds>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Int32,
    ffi.Double,
    ffi.Int32,
    ffi.Double,
    ffi.Uint32,
    ffi.Pointer<MblCameraOptions>,
  )
>()
external int mbl_map_camera_for_lat_lng_bounds(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<MblLatLngBounds> bounds,
  double pad_top,
  double pad_right,
  double pad_bottom,
  double pad_left,
  int has_bearing,
  double bearing,
  int has_pitch,
  double pitch,
  int timeout_ms,
  ffi.Pointer<MblCameraOptions> out_camera,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<MblCameraOptions>,
    ffi.Uint32,
    ffi.Pointer<MblLatLngBounds>,
  )
>()
external int mbl_map_lat_lng_bounds_for_camera(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<MblCameraOptions> camera,
  int timeout_ms,
  ffi.Pointer<MblLatLngBounds> out_bounds,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<MblMap>, ffi.Pointer<MblBoundOptions>)
>()
external void mbl_map_set_bounds(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<MblBoundOptions> bounds,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Uint32,
    ffi.Pointer<MblBoundOptions>,
  )
>()
external int mbl_map_get_bounds(
  ffi.Pointer<MblMap> map,
  int timeout_ms,
  ffi.Pointer<MblBoundOptions> out_bounds,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Int32)>()
external void mbl_map_set_constrain_mode(ffi.Pointer<MblMap> map, int mode);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Double,
    ffi.Double,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Int>,
    ffi.Uint64,
  )
>()
external int mbl_map_pixel_for_lat_lng(
  ffi.Pointer<MblMap> map,
  double lat,
  double lng,
  ffi.Pointer<ffi.Double> out_x,
  ffi.Pointer<ffi.Double> out_y,
  ffi.Pointer<ffi.Int> out_visible,
  int generation,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Double>,
    ffi.Uint32,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Int>,
    ffi.Uint64,
  )
>()
external int mbl_map_pixels_for_lat_lngs(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Double> in_lat_lng,
  int count,
  ffi.Pointer<ffi.Double> out_xy,
  ffi.Pointer<ffi.Int> out_visible,
  int generation,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Double,
    ffi.Double,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    ffi.Uint64,
  )
>()
external int mbl_map_lat_lng_for_pixel(
  ffi.Pointer<MblMap> map,
  double x,
  double y,
  ffi.Pointer<ffi.Double> out_lat,
  ffi.Pointer<ffi.Double> out_lng,
  int generation,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external int mbl_map_add_source_json(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> id,
  ffi.Pointer<ffi.Char> json,
  ffi.Pointer<ffi.Char> err,
  int err_len,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external int mbl_map_add_layer_json(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> json,
  ffi.Pointer<ffi.Char> before_id,
  ffi.Pointer<ffi.Char> err,
  int err_len,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external int mbl_map_set_geojson_data(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  ffi.Pointer<ffi.Char> geojson,
  ffi.Pointer<ffi.Char> err,
  int err_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Pointer<ffi.Char>)>()
external void mbl_map_remove_layer(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> id,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<MblMap>, ffi.Pointer<ffi.Char>, ffi.Uint32)
>()
external int mbl_map_has_image(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> id,
  int timeout_ms,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<MblMap>, ffi.Uint32)>()
external ffi.Pointer<ffi.Char> mbl_map_get_image_ids(
  ffi.Pointer<MblMap> map,
  int timeout_ms,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> mbl_map_get_source_json(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  int timeout_ms,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<MblMap>, ffi.Uint32)>()
external ffi.Pointer<ffi.Char> mbl_map_get_source_ids(
  ffi.Pointer<MblMap> map,
  int timeout_ms,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external int mbl_map_set_layer_property(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> layer_id,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Char> value_json,
  ffi.Pointer<ffi.Char> err,
  int err_len,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external void mbl_map_move_layer(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> layer_id,
  ffi.Pointer<ffi.Char> before_id,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> mbl_map_get_layer_property(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> layer_id,
  ffi.Pointer<ffi.Char> name,
  int timeout_ms,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<MblMap>, ffi.Uint32)>()
external ffi.Pointer<ffi.Char> mbl_map_get_layer_ids(
  ffi.Pointer<MblMap> map,
  int timeout_ms,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> mbl_map_get_layer_json(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> layer_id,
  int timeout_ms,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Pointer<ffi.Char>)>()
external void mbl_map_remove_source(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> id,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Float,
    ffi.Int,
  )
>()
external void mbl_map_add_image(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> id,
  ffi.Pointer<ffi.Uint8> rgba,
  int width,
  int height,
  double pixel_ratio,
  int sdf,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Pointer<ffi.Char>)>()
external void mbl_map_remove_image(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> id,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<MblMap>, ffi.Int32, ffi.Int32, ffi.Int)
>()
external void mbl_map_set_transition_options(
  ffi.Pointer<MblMap> map,
  int duration_ms,
  int delay_ms,
  int placement_transitions,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<MblMap>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> mbl_map_query_rendered_features(
  ffi.Pointer<MblMap> map,
  double min_x,
  double min_y,
  double max_x,
  double max_y,
  ffi.Pointer<ffi.Char> layer_ids,
  ffi.Pointer<ffi.Char> filter_json,
  int timeout_ms,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> user,
          ffi.Pointer<ffi.Char> json,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_map_query_rendered_features_async(
  ffi.Pointer<MblMap> map,
  double min_x,
  double min_y,
  double max_x,
  double max_y,
  ffi.Pointer<ffi.Char> layer_ids,
  ffi.Pointer<ffi.Char> filter_json,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void> user, ffi.Pointer<ffi.Char> json)
    >
  >
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> mbl_map_query_source_features(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  ffi.Pointer<ffi.Char> source_layers,
  ffi.Pointer<ffi.Char> filter_json,
  int timeout_ms,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int mbl_map_get_cluster_expansion_zoom(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  int cluster_id,
  int timeout_ms,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> mbl_map_get_cluster_children(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  int cluster_id,
  int timeout_ms,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> mbl_map_get_cluster_leaves(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  int cluster_id,
  int limit,
  int offset,
  int timeout_ms,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external void mbl_map_set_feature_state(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  ffi.Pointer<ffi.Char> source_layer,
  ffi.Pointer<ffi.Char> feature_id,
  ffi.Pointer<ffi.Char> state_json,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> mbl_map_get_feature_state(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  ffi.Pointer<ffi.Char> source_layer,
  ffi.Pointer<ffi.Char> feature_id,
  int timeout_ms,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external void mbl_map_remove_feature_state(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> source_id,
  ffi.Pointer<ffi.Char> source_layer,
  ffi.Pointer<ffi.Char> feature_id,
  ffi.Pointer<ffi.Char> state_key,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void mbl_string_free(ffi.Pointer<ffi.Char> s);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<MblMap>)>()
external int mbl_map_presented_generation(ffi.Pointer<MblMap> map);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<MblMap>)>()
external int mbl_map_proj_generation(ffi.Pointer<MblMap> map);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> user)>
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void mbl_map_set_frame_callback(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> user)>>
  callback,
  ffi.Pointer<ffi.Void> user,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<MblMap>, ffi.Uint32)>()
external int mbl_map_await_frame(ffi.Pointer<MblMap> map, int timeout_ms);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int mbl_map_copy_frame(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Uint8> dst,
  int dst_capacity,
  ffi.Pointer<ffi.Uint32> out_width,
  ffi.Pointer<ffi.Uint32> out_height,
  ffi.Pointer<ffi.Uint32> out_stride,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Int)>()
external void mbl_map_set_zero_copy(ffi.Pointer<MblMap> map, int enabled);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Int)>()
external void mbl_map_set_pixel_format_bgra(ffi.Pointer<MblMap> map, int bgra);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<MblMap>)>()
external ffi.Pointer<ffi.Void> mbl_map_current_iosurface(
  ffi.Pointer<MblMap> map,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<MblMap>, ffi.Pointer<MblGlDmabufFrame>)
>()
external int mbl_map_current_gl_image(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<MblGlDmabufFrame> out,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<MblMap>)>()
external int mbl_map_gl_active(ffi.Pointer<MblMap> map);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int mbl_map_current_d3d_handle(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Pointer<ffi.Void>> out_handle,
  ffi.Pointer<ffi.Uint32> out_width,
  ffi.Pointer<ffi.Uint32> out_height,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<MblMap>)>()
external int mbl_map_d3d_active(ffi.Pointer<MblMap> map);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int mbl_map_add_model(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> layer_id,
  ffi.Pointer<ffi.Char> glb_path,
  double lat,
  double lng,
  double scale,
  double heading_deg,
  double spin_dps,
  double elevation_m,
  ffi.Pointer<ffi.Char> out_error,
  int error_capacity,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
  )
>()
external void mbl_map_set_model_transform(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> layer_id,
  double lat,
  double lng,
  double scale,
  double heading_deg,
  double elevation_m,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<MblMap>)>()
external int mbl_map_frame_count(ffi.Pointer<MblMap> map);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<ffi.Char>)>()
external int mbl_model_part_count(ffi.Pointer<ffi.Char> glb_path);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>, ffi.Pointer<ffi.Char>)>()
external void mbl_map_remove_model(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> layer_id,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<MblMap>,
    ffi.Pointer<ffi.Char>,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Double,
  )
>()
external void mbl_map_add_test_model(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> layer_id,
  double lat,
  double lng,
  double metres_per_unit,
  double spin_dps,
  double elevation_m,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>)>()
external void mbl_map_trigger_repaint(ffi.Pointer<MblMap> map);

@ffi.Native<ffi.Int Function(ffi.Pointer<MblMap>, ffi.Pointer<ffi.Char>)>()
external int mbl_map_write_png(
  ffi.Pointer<MblMap> map,
  ffi.Pointer<ffi.Char> path,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<MblMap>)>()
external void mbl_map_destroy(ffi.Pointer<MblMap> map);

final class MblMap extends ffi.Opaque {}

final class MblCameraOptions extends ffi.Struct {
  @ffi.Int32()
  external int has_center;

  @ffi.Double()
  external double center_lat;

  @ffi.Double()
  external double center_lng;

  @ffi.Int32()
  external int has_zoom;

  @ffi.Double()
  external double zoom;

  @ffi.Int32()
  external int has_bearing;

  @ffi.Double()
  external double bearing;

  @ffi.Int32()
  external int has_pitch;

  @ffi.Double()
  external double pitch;

  @ffi.Int32()
  external int has_roll;

  @ffi.Double()
  external double roll;

  @ffi.Int32()
  external int has_padding;

  @ffi.Double()
  external double padding_top;

  @ffi.Double()
  external double padding_right;

  @ffi.Double()
  external double padding_bottom;

  @ffi.Double()
  external double padding_left;

  @ffi.Int32()
  external int has_anchor;

  @ffi.Double()
  external double anchor_x;

  @ffi.Double()
  external double anchor_y;
}

final class MblAnimationOptions extends ffi.Struct {
  @ffi.Int32()
  external int has_duration;

  @ffi.Uint32()
  external int duration_ms;

  @ffi.Int32()
  external int has_easing;

  @ffi.Double()
  external double easing_x1;

  @ffi.Double()
  external double easing_y1;

  @ffi.Double()
  external double easing_x2;

  @ffi.Double()
  external double easing_y2;

  @ffi.Int32()
  external int has_speed;

  @ffi.Double()
  external double speed;

  @ffi.Int32()
  external int has_apex_zoom;

  @ffi.Double()
  external double apex_zoom;
}

final class MblLatLngBounds extends ffi.Struct {
  @ffi.Double()
  external double sw_lat;

  @ffi.Double()
  external double sw_lng;

  @ffi.Double()
  external double ne_lat;

  @ffi.Double()
  external double ne_lng;
}

final class MblBoundOptions extends ffi.Struct {
  @ffi.Int32()
  external int has_bounds;

  external MblLatLngBounds bounds;

  @ffi.Int32()
  external int has_min_zoom;

  @ffi.Double()
  external double min_zoom;

  @ffi.Int32()
  external int has_max_zoom;

  @ffi.Double()
  external double max_zoom;

  @ffi.Int32()
  external int has_min_pitch;

  @ffi.Double()
  external double min_pitch;

  @ffi.Int32()
  external int has_max_pitch;

  @ffi.Double()
  external double max_pitch;
}

final class MblGlDmabufFrame extends ffi.Opaque {}
