// swiftgen config for maplibre_flutter_ios (CLAUDE.md §5b).
//
// Binds our own @objc shim classes (MapLibreController, MapRegistry) — already
// ObjC-compatible, so we use ObjCCompatibleSwiftFileInput (no wrapper layer).
// Their surface is primitives + String, so no MLN* type is pulled in. The
// MapLibre-touching code lives in MapLibreMapBackend.swift, which is NOT an
// input (swiftgen compiles its inputs against the bare SDK).
//
// Outputs: Dart bindings (lib/src/...g.dart) + ObjC glue (.m). Both committed.
// Run from this package root:  dart run tool/swiftgen.dart
import 'dart:io';

import 'package:ffigen/ffigen.dart' as fg;
import 'package:logging/logging.dart';
import 'package:pub_semver/pub_semver.dart';
import 'package:swiftgen/swiftgen.dart';

const _sources = 'ios/maplibre_flutter_ios/Sources/maplibre_flutter_ios';

Future<void> main() async {
  final logger = Logger('swiftgen')
    ..onRecord.listen((r) => stderr.writeln('${r.level.name}: ${r.message}'));

  // §5b workaround: resolve the SDK path/version via xcrun rather than
  // Target.iOSArm64Latest() (which can throw FormatException).
  final sdkPath = _xcrun(['--sdk', 'iphoneos', '--show-sdk-path']);

  await SwiftGenerator(
    target: Target(triple: 'arm64-apple-ios13.0', sdk: Uri.directory(sdkPath)),
    inputs: [
      ObjCCompatibleSwiftFileInput(
        files: [
          Uri.file('$_sources/MapLibreController.swift'),
          Uri.file('$_sources/MapRegistry.swift'),
        ],
      ),
    ],
    output: Output(
      module: 'maplibre_flutter_ios',
      dartFile: Uri.file('lib/src/maplibre_flutter_ios_bindings.g.dart'),
      objectiveCFile: Uri.file('$_sources/maplibre_flutter_ios.m'),
      preamble: '''
// GENERATED by tool/swiftgen.dart — do not edit. Regenerate after changing the
// @objc MapLibreController / MapRegistry surface.
''',
    ),
    ffigen: FfiGeneratorOptions(
      objectiveC: fg.ObjectiveC(
        externalVersions: fg.ExternalVersions(
          ios: fg.Versions(min: Version(13, 0, 0)),
        ),
        // Only our two shim interfaces — not NSObject/NSString etc. (§5b).
        interfaces: fg.Interfaces(
          include: (decl) =>
              decl.originalName == 'MapLibreController' ||
              decl.originalName == 'MapRegistry',
        ),
      ),
    ),
  ).generate(logger: logger, tempDirectory: Directory.systemTemp.uri);
}

String _xcrun(List<String> args) {
  final r = Process.runSync('xcrun', args);
  if (r.exitCode != 0) {
    throw StateError('xcrun ${args.join(' ')} failed: ${r.stderr}');
  }
  return (r.stdout as String).trim();
}
