// Generates FEATURE_MATRIX.generated.md from the CODE.
//
//   dart run tool/generate_feature_matrix.dart
//
// WHY THIS EXISTS: the hand-maintained matrix was audited and ~44% of sampled
// cells were wrong — five hours after someone had hand-fixed it. A table that
// says a feature is wired when it is not is worse than no table, because it is
// consulted instead of the code. Everything derivable is derived here; the
// judgement that is left lives as prose in FEATURE_MATRIX.md.
//
// What it reads, and nothing else:
//   * the FFI_PLUGIN_EXPORT declarations in maplibre_flutter_core.h  → the C ABI
//   * `abstract interface class` declarations in the platform interface
//                                                      → the capability surface
//   * each platform controller's `implements` clause   → who has what
//
// Deliberately syntactic. It does not run the analyzer: the point is a check
// that cannot drift from the source, and adding a resolution step would make it
// something people skip when it breaks.
library;

import 'dart:io';

/// Repo-relative paths, resolved from this script's location so it can be run
/// from anywhere.
final _repoRoot = Directory.current.path.endsWith('packages/maplibre_flutter')
    ? Directory.current.parent.parent.path
    : Directory.current.path;

String _p(String relative) => '$_repoRoot/$relative';

/// The tiers, in the order the matrix shows them, as their package `lib/`.
///
/// A DIRECTORY, not the controller file, because not every capability hangs off
/// the map controller: `MapLibreOfflineStore` is reached through
/// `MapLibreFlutterPlatform.offlineStore` and implemented by a class of its own,
/// and scanning only the controller reported it as wired nowhere — which is the
/// exact failure mode this generator exists to end.
const _tiers = <String, String>{
  'macOS': 'packages/maplibre_flutter_macos/lib',
  'iOS': 'packages/maplibre_flutter_ios/lib',
  'Android': 'packages/maplibre_flutter_android/lib',
  'Windows': 'packages/maplibre_flutter_windows/lib',
  'Linux': 'packages/maplibre_flutter_linux/lib',
  'Web (WASM)': 'packages/maplibre_flutter_web/lib',
};

void main() {
  final buffer = StringBuffer()
    ..writeln(
      '<!-- GENERATED by packages/maplibre_flutter/tool/'
      'generate_feature_matrix.dart — DO NOT EDIT. -->',
    )
    ..writeln(
      '<!-- Regenerate with: dart run tool/generate_feature_matrix.dart -->',
    )
    ..writeln()
    ..writeln('# Feature matrix (generated)')
    ..writeln()
    ..writeln('Derived from the source, so it cannot disagree with it. The')
    ..writeln('judgement — what is *worth* having, and what "works" means on a')
    ..writeln('tier nobody has run — is prose in `FEATURE_MATRIX.md`.')
    ..writeln()
    ..writeln(
      '**A tick here means the code is WIRED, not that it has been RUN.**',
    )
    ..writeln('Only macOS and iOS have been exercised on hardware; see')
    ..writeln('`docs/cross-platform-continuation.md`.')
    ..writeln();

  _writeCapabilities(buffer);
  _writeAbi(buffer);

  final out = File(_p('FEATURE_MATRIX.generated.md'));
  out.writeAsStringSync(buffer.toString());
  stdout.writeln('wrote ${out.path}');
}

/// Capability interfaces × tiers, from the `implements` clauses.
void _writeCapabilities(StringBuffer buffer) {
  final capabilities = _capabilityInterfaces();
  final implemented = <String, Set<String>>{
    for (final tier in _tiers.keys) tier: _implementedBy(_tiers[tier]!),
  };

  buffer
    ..writeln('## Capabilities by tier')
    ..writeln()
    ..writeln(
      'Optional capabilities are feature-detected with `is` '
      '(CLAUDE.md §3), so this table is exactly the set of `implements` '
      'clauses across each tier\'s package.',
    )
    ..writeln()
    ..writeln('| Capability | ${_tiers.keys.join(' | ')} |')
    ..writeln('| --- | ${_tiers.keys.map((_) => '---').join(' | ')} |');

  for (final capability in capabilities.keys.toList()..sort()) {
    final cells = _tiers.keys
        .map((t) => implemented[t]!.contains(capability) ? '✅' : '—')
        .join(' | ');
    buffer.writeln(
      '| `$capability` (${capabilities[capability]} members) '
      '| $cells |',
    );
  }
  buffer.writeln();
}

/// Every `abstract interface class` in the platform interface, with how many
/// members it declares.
Map<String, int> _capabilityInterfaces() {
  final dir = Directory(
    _p('packages/maplibre_flutter_platform_interface/lib/src'),
  );
  final found = <String, int>{};
  for (final file in dir.listSync(recursive: true).whereType<File>()) {
    if (!file.path.endsWith('.dart')) continue;
    final source = file.readAsStringSync();
    for (final match in RegExp(
      r'abstract interface class (\w+)',
    ).allMatches(source)) {
      final name = match.group(1)!;
      found[name] = _memberCount(source, match.end);
    }
  }
  return found;
}

/// Counts declarations in the class body starting at [from].
///
/// Brace-matched rather than line-counted: a member list that miscounts is a
/// number nobody can trust, and a wrong number in a generated file is exactly
/// the failure this tool exists to end.
int _memberCount(String source, int from) {
  final open = source.indexOf('{', from);
  if (open < 0) return 0;
  var depth = 0;
  var end = open;
  for (var i = open; i < source.length; i++) {
    if (source[i] == '{') depth++;
    if (source[i] == '}') {
      depth--;
      if (depth == 0) {
        end = i;
        break;
      }
    }
  }
  final body = source.substring(open, end);
  // Members of an interface are all abstract, so each ends in `;` at depth 1.
  return RegExp(r';').allMatches(body).length;
}

/// Every interface any class in a tier's package declares it implements.
///
/// Every class in the package, not just the controller, and every `implements`
/// clause in each file rather than the first — see [_tiers].
Set<String> _implementedBy(String libPath) {
  final dir = Directory(_p(libPath));
  if (!dir.existsSync()) return <String>{};
  final found = <String>{};
  for (final file in dir.listSync(recursive: true).whereType<File>()) {
    if (!file.path.endsWith('.dart')) continue;
    for (final match in RegExp(
      r'class\s+\w+[^{;]*?implements\s+([^{]+)\{',
      dotAll: true,
    ).allMatches(file.readAsStringSync())) {
      found.addAll(
        match
            .group(1)!
            .split(',')
            .map((s) => s.trim().split('<').first.trim())
            .where((s) => s.isNotEmpty),
      );
    }
  }
  return found;
}

/// The C ABI surface, grouped by the header's own section comments.
void _writeAbi(StringBuffer buffer) {
  final header = File(
    _p('packages/maplibre_flutter_core/src/maplibre_flutter_core.h'),
  );
  final source = header.readAsStringSync();
  final functions = RegExp(
    r'FFI_PLUGIN_EXPORT\s+[\w *]+?\b(mbl_\w+)\s*\(',
  ).allMatches(source).map((m) => m.group(1)!).toList();

  buffer
    ..writeln('## C ABI surface')
    ..writeln()
    ..writeln(
      'Every `FFI_PLUGIN_EXPORT` in `maplibre_flutter_core.h` — the '
      'whole engine surface the Dart tiers can reach. ',
    )
    ..writeln('**${functions.length} entry points.**')
    ..writeln()
    ..writeln('<details><summary>Full list</summary>')
    ..writeln();
  for (final name in functions) {
    buffer.writeln('- `$name`');
  }
  buffer
    ..writeln()
    ..writeln('</details>')
    ..writeln();
}
