// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// GENERATED by tool/jnigen.dart — do not edit. Regenerate after changing the
// Kotlin MapRegistry / MapLibreController public API.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `dev.maplibreflutter.maplibre_flutter_android.MapRegistry`
extension type MapRegistry._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/maplibreflutter/maplibre_flutter_android/MapRegistry',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MapRegistry> type = $MapRegistry$Type$();
  static final _id_register = _class.staticMethodId(
    r'register',
    r'(I)Ldev/maplibreflutter/maplibre_flutter_android/MapLibreController;',
  );

  static final _register =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public dev.maplibreflutter.maplibre_flutter_android.MapLibreController register(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static MapLibreController? register(core$_.int i) {
    return _register(
      _class.reference.pointer,
      _id_register.pointer,
      i,
    ).object<MapLibreController?>();
  }

  static final _id_get = _class.staticMethodId(
    r'get',
    r'(I)Ldev/maplibreflutter/maplibre_flutter_android/MapLibreController;',
  );

  static final _get =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public dev.maplibreflutter.maplibre_flutter_android.MapLibreController get(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static MapLibreController? get(core$_.int i) {
    return _get(
      _class.reference.pointer,
      _id_get.pointer,
      i,
    ).object<MapLibreController?>();
  }

  static final _id_unregister = _class.staticMethodId(r'unregister', r'(I)V');

  static final _unregister =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public void unregister(int i)`
  static void unregister(core$_.int i) {
    _unregister(_class.reference.pointer, _id_unregister.pointer, i).check();
  }
}

final class $MapRegistry$Type$ extends jni$_.JType<MapRegistry> {
  @jni$_.internal
  const $MapRegistry$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/maplibreflutter/maplibre_flutter_android/MapRegistry;';
}

/// from: `dev.maplibreflutter.maplibre_flutter_android.MapLibreController`
extension type MapLibreController._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/maplibreflutter/maplibre_flutter_android/MapLibreController',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MapLibreController> type =
      $MapLibreController$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory MapLibreController() {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
    ).object<MapLibreController>();
  }
}

extension MapLibreController$$Methods on MapLibreController {
  static final _id_attachMap = MapLibreController._class.instanceMethodId(
    r'attachMap',
    r'(Lorg/maplibre/android/maps/MapLibreMap;)V',
  );

  static final _attachMap =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void attachMap(org.maplibre.android.maps.MapLibreMap mapLibreMap)`
  void attachMap(jni$_.JObject? mapLibreMap) {
    final _$mapLibreMap = mapLibreMap?.reference ?? jni$_.jNullReference;
    _attachMap(
      reference.pointer,
      _id_attachMap.pointer,
      _$mapLibreMap.pointer,
    ).check();
  }

  static final _id_get$isReady = MapLibreController._class.instanceMethodId(
    r'isReady',
    r'()Z',
  );

  static final _get$isReady =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isReady()`
  core$_.bool get isReady {
    return _get$isReady(reference.pointer, _id_get$isReady.pointer).boolean;
  }

  static final _id_get$lat = MapLibreController._class.instanceMethodId(
    r'getLat',
    r'()D',
  );

  static final _get$lat =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallDoubleMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public double getLat()`
  core$_.double get lat {
    return _get$lat(reference.pointer, _id_get$lat.pointer).doubleFloat;
  }

  static final _id_get$lng = MapLibreController._class.instanceMethodId(
    r'getLng',
    r'()D',
  );

  static final _get$lng =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallDoubleMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public double getLng()`
  core$_.double get lng {
    return _get$lng(reference.pointer, _id_get$lng.pointer).doubleFloat;
  }

  static final _id_get$zoom = MapLibreController._class.instanceMethodId(
    r'getZoom',
    r'()D',
  );

  static final _get$zoom =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallDoubleMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public double getZoom()`
  core$_.double get zoom {
    return _get$zoom(reference.pointer, _id_get$zoom.pointer).doubleFloat;
  }

  static final _id_get$bearing = MapLibreController._class.instanceMethodId(
    r'getBearing',
    r'()D',
  );

  static final _get$bearing =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallDoubleMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public double getBearing()`
  core$_.double get bearing {
    return _get$bearing(reference.pointer, _id_get$bearing.pointer).doubleFloat;
  }

  static final _id_get$pitch = MapLibreController._class.instanceMethodId(
    r'getPitch',
    r'()D',
  );

  static final _get$pitch =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallDoubleMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public double getPitch()`
  core$_.double get pitch {
    return _get$pitch(reference.pointer, _id_get$pitch.pointer).doubleFloat;
  }

  static final _id_moveCamera = MapLibreController._class.instanceMethodId(
    r'moveCamera',
    r'(DDDDDJ)V',
  );

  static final _moveCamera =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Double,
                    jni$_.Double,
                    jni$_.Double,
                    jni$_.Double,
                    jni$_.Double,
                    jni$_.Int64,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.double,
              core$_.double,
              core$_.double,
              core$_.double,
              core$_.double,
              core$_.int,
            )
          >();

  /// from: `public void moveCamera(double d, double d1, double d2, double d3, double d4, long j)`
  void moveCamera(
    core$_.double d,
    core$_.double d1,
    core$_.double d2,
    core$_.double d3,
    core$_.double d4,
    core$_.int j,
  ) {
    _moveCamera(
      reference.pointer,
      _id_moveCamera.pointer,
      d,
      d1,
      d2,
      d3,
      d4,
      j,
    ).check();
  }

  static final _id_set$style = MapLibreController._class.instanceMethodId(
    r'setStyle',
    r'(Ljava/lang/String;)V',
  );

  static final _set$style =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void setStyle(java.lang.String string)`
  set style(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    _set$style(
      reference.pointer,
      _id_set$style.pointer,
      _$string.pointer,
    ).check();
  }
}

final class $MapLibreController$Type$ extends jni$_.JType<MapLibreController> {
  @jni$_.internal
  const $MapLibreController$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/maplibreflutter/maplibre_flutter_android/MapLibreController;';
}
