// GENERATED by tool/swiftgen.dart — do not edit. Regenerate after changing the
// @objc MapLibreController / MapRegistry surface.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

late final _class_MapLibreController = objc.getClass(
  "maplibre_flutter_ios.MapLibreController",
);
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_lat = objc.registerName("lat");
final _objc_msgSend_1ukqyt8 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Double Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1ukqyt8Fpret = objc.msgSendFpretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Double Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_setLat_ = objc.registerName("setLat:");
final _objc_msgSend_hwm8nu = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Double,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        double,
      )
    >();
late final _sel_lng = objc.registerName("lng");
late final _sel_setLng_ = objc.registerName("setLng:");
late final _sel_zoom = objc.registerName("zoom");
late final _sel_setZoom_ = objc.registerName("setZoom:");
late final _sel_bearing = objc.registerName("bearing");
late final _sel_setBearing_ = objc.registerName("setBearing:");
late final _sel_pitch = objc.registerName("pitch");
late final _sel_setPitch_ = objc.registerName("setPitch:");
late final _sel_isReady = objc.registerName("isReady");
final _objc_msgSend_91o635 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_setIsReady_ = objc.registerName("setIsReady:");
final _objc_msgSend_1s56lr9 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Bool,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        bool,
      )
    >();
late final _sel_moveCameraWithLat_lng_zoom_bearing_pitch_durationMs_ = objc
    .registerName("moveCameraWithLat:lng:zoom:bearing:pitch:durationMs:");
final _objc_msgSend_1h9la3o = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Double,
          ffi.Double,
          ffi.Double,
          ffi.Double,
          ffi.Double,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        double,
        double,
        double,
        double,
        double,
        int,
      )
    >();
late final _sel_setStyle_ = objc.registerName("setStyle:");
final _objc_msgSend_xtuoz7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
late final _sel_init = objc.registerName("init");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_new = objc.registerName("new");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");

/// Thin, swiftgen-bound controller for one live map (CLAUDE.md §5b/§5d).
/// Dart calls the <code>@objc public</code> primitive surface over the Objective-C runtime;
/// commands forward to the MapLibre-backed [ops]. The camera is cached (written
/// by the backend from the map’s delegate) so the getters are a plain read. The
/// surface is primitives + <code>String</code> only, so swiftgen never sees an <code>MLN*</code> type.
extension type MapLibreController._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [MapLibreController] that points to the same underlying object as [other].
  MapLibreController.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [MapLibreController] that wraps the given raw object pointer.
  MapLibreController.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MapLibreController].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_MapLibreController,
  );

  /// alloc
  static MapLibreController alloc() {
    final $ret = _objc_msgSend_151sglz(_class_MapLibreController, _sel_alloc);
    return MapLibreController.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static MapLibreController allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_MapLibreController,
      _sel_allocWithZone_,
      zone,
    );
    return MapLibreController.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static MapLibreController new$() {
    final $ret = _objc_msgSend_151sglz(_class_MapLibreController, _sel_new);
    return MapLibreController.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of MapLibreController constructed with the default `new` method.
  MapLibreController() : this.as(new$().object$);
}

extension MapLibreController$Methods on MapLibreController {
  /// bearing
  double get bearing {
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_bearing)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_bearing);
  }

  /// init
  MapLibreController init() {
    objc.checkOsVersionInternal(
      'MapLibreController.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MapLibreController.fromPointer($ret, retain: false, release: true);
  }

  /// isReady
  bool get isReady {
    return _objc_msgSend_91o635(object$.ref.pointer, _sel_isReady);
  }

  /// lat
  double get lat {
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_lat)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_lat);
  }

  /// lng
  double get lng {
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_lng)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_lng);
  }

  /// moveCameraWithLat:lng:zoom:bearing:pitch:durationMs:
  void moveCameraWithLat(
    double lat, {
    required double lng,
    required double zoom,
    required double bearing,
    required double pitch,
    required int durationMs,
  }) {
    _objc_msgSend_1h9la3o(
      object$.ref.pointer,
      _sel_moveCameraWithLat_lng_zoom_bearing_pitch_durationMs_,
      lat,
      lng,
      zoom,
      bearing,
      pitch,
      durationMs,
    );
  }

  /// pitch
  double get pitch {
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_pitch)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_pitch);
  }

  /// setBearing:
  set bearing(double value) {
    _objc_msgSend_hwm8nu(object$.ref.pointer, _sel_setBearing_, value);
  }

  /// setIsReady:
  set isReady(bool value) {
    _objc_msgSend_1s56lr9(object$.ref.pointer, _sel_setIsReady_, value);
  }

  /// setLat:
  set lat(double value) {
    _objc_msgSend_hwm8nu(object$.ref.pointer, _sel_setLat_, value);
  }

  /// setLng:
  set lng(double value) {
    _objc_msgSend_hwm8nu(object$.ref.pointer, _sel_setLng_, value);
  }

  /// setPitch:
  set pitch(double value) {
    _objc_msgSend_hwm8nu(object$.ref.pointer, _sel_setPitch_, value);
  }

  /// setStyle:
  void setStyle(objc.NSString uri) {
    _objc_msgSend_xtuoz7(object$.ref.pointer, _sel_setStyle_, uri.ref.pointer);
  }

  /// setZoom:
  set zoom(double value) {
    _objc_msgSend_hwm8nu(object$.ref.pointer, _sel_setZoom_, value);
  }

  /// zoom
  double get zoom {
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_zoom)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_zoom);
  }
}

late final _class_MapRegistry = objc.getClass(
  "maplibre_flutter_ios.MapRegistry",
);
late final _sel_register_ = objc.registerName("register:");
final _objc_msgSend_qugqlf = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
late final _sel_get_ = objc.registerName("get:");
late final _sel_unregister_ = objc.registerName("unregister:");
final _objc_msgSend_4sp4xj = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();

/// Maps the Dart-minted <code>mapId</code> to its [MapLibreController].
/// Dart mints a <code>mapId</code>, passes it via <code>creationParams</code>, and looks the
/// controller up here over swiftgen — control flows Dart → ObjC runtime →
/// controller with no data-path method channel (CLAUDE.md §10). Foundation-only
/// so swiftgen can compile it (see [MapLibreController]).
extension type MapRegistry._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [MapRegistry] that points to the same underlying object as [other].
  MapRegistry.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [MapRegistry] that wraps the given raw object pointer.
  MapRegistry.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MapRegistry].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_MapRegistry,
  );

  /// alloc
  static MapRegistry alloc() {
    final $ret = _objc_msgSend_151sglz(_class_MapRegistry, _sel_alloc);
    return MapRegistry.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static MapRegistry allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_MapRegistry,
      _sel_allocWithZone_,
      zone,
    );
    return MapRegistry.fromPointer($ret, retain: false, release: true);
  }

  /// The controller for <code>mapId</code>, or nil if the view does not exist (yet).
  static MapLibreController? get(int mapId) {
    final $ret = _objc_msgSend_qugqlf(_class_MapRegistry, _sel_get_, mapId);
    return $ret.address == 0
        ? null
        : MapLibreController.fromPointer($ret, retain: true, release: true);
  }

  /// new
  static MapRegistry new$() {
    final $ret = _objc_msgSend_151sglz(_class_MapRegistry, _sel_new);
    return MapRegistry.fromPointer($ret, retain: false, release: true);
  }

  /// Create and register a controller for <code>mapId</code> (called from the view factory).
  static MapLibreController register(int mapId) {
    final $ret = _objc_msgSend_qugqlf(
      _class_MapRegistry,
      _sel_register_,
      mapId,
    );
    return MapLibreController.fromPointer($ret, retain: true, release: true);
  }

  /// unregister:
  static void unregister(int mapId) {
    _objc_msgSend_4sp4xj(_class_MapRegistry, _sel_unregister_, mapId);
  }

  /// Returns a new instance of MapRegistry constructed with the default `new` method.
  MapRegistry() : this.as(new$().object$);
}

extension MapRegistry$Methods on MapRegistry {
  /// init
  MapRegistry init() {
    objc.checkOsVersionInternal(
      'MapRegistry.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MapRegistry.fromPointer($ret, retain: false, release: true);
  }
}
