// jnigen config for maplibre_flutter_android (CLAUDE.md §5a).
//
// Generates Dart bindings for our own thin Kotlin classes — MapRegistry and
// MapLibreController — NOT the MapLibre SDK. Their public surface is primitives
// + String, so referenced `org.maplibre.*` types stay opaque and the binding
// stays small. The generated file is committed; never hand-edit it.
//
// Prerequisites (CLAUDE.md §5a):
//   * The Android project must be built at least once (we resolve the classpath
//     via `addGradleDeps` against the example app, which includes this plugin).
//   * Run from this package root:  dart run tool/jnigen.dart
//
// If generation throws "Unexpected end of input", rebuild gradle without cache
// (see CLAUDE.md §5a) then re-run.
import 'package:jnigen/jnigen.dart';

Future<void> main() async {
  await generateJniBindings(
    Config(
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          path: Uri.file('lib/src/maplibre_flutter_android_bindings.g.dart'),
          structure: OutputStructure.singleFile,
        ),
      ),
      classes: [
        'dev.maplibreflutter.maplibre_flutter_android.MapRegistry',
        'dev.maplibreflutter.maplibre_flutter_android.MapLibreController',
      ],
      androidSdkConfig: AndroidSdkConfig(
        addGradleDeps: true,
        // The buildable app that includes this plugin; jnigen runs gradle here
        // to resolve the compile classpath (MapLibre SDK, androidx).
        androidExample: '../maplibre_flutter/example',
      ),
      preamble: '''
// GENERATED by tool/jnigen.dart — do not edit. Regenerate after changing the
// Kotlin MapRegistry / MapLibreController public API.
''',
    ),
  );
}
